name: Auto Deploy AWS Network

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change AWS region if needed

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file aws-network.yml \
            --stack-name my-network-stack \
            --capabilities CAPABILITY_NAMED_IAM